version: '3'

services:
  # django web server
  django:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=postgres
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=coffeecalorie
      - DJANGO_DB_USERNAME=hanyonghee
      - DJANGO_DB_PASSWORD=samplesecret
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:postgres
    tty: true
    command:
      - bash
      - -c
      - |
        python /srv/projects/app/manage.py migrate
        supervisord -n
        redis-server
